prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        app: frontend
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
admissionWebhooks:
  enabled: false
